### PR TITLE
make it possible to override filters

### PR DESCRIPTION
**Pull request by tiptop96**

### CODE REVIEW

**Comment by tiptop96** [comment]
Hey!

We anticipate a usecase where there is only one `region` making the filter redundant so it would be cool to be able to override them.

Another possible solution would be too have the possibility to disable the filter if there is only one possible value.

What are your thoughts?

**Comment by joshreisner** [comment]
could you tell me more about this use-case? it's currently possible to hide the region dropdown if you don't have any `region` or `city` keys in your data

**Comment by tiptop96** [comment]
Ahh I miss-understood the field. But that is good to know. I think we can scrap this PR.

**Comment by joshreisner** [comment]
ok! i'm not opposed to bringing it back someday if you wanted to be able to re-order the controls. 

> Another possible solution would be too have the possibility to disable the filter if there is only one possible value.

yes, it might make sense to hide any filter (including time, day, etc) if it applies to every meeting in the list, since it would not be an aid to searching, and just be clutter. in the case of your single region, that would result in the region filter being hidden without having to change the config.

**Pull request closed without merging**
