### PR TITLE
Update ja.ts

### PR DESCRIPTION
**Pull request by Hiro-Tokyo**
I made a couple of changes. 

Please review it and approve my request.

Hiro

### CODE REVIEW

**Review by joshreisner — APPROVED** [review]
🥇

**Comment by Hiro-Tokyo** [comment]
Hi Josh, thank you for approving my request. Seems this patch does not reflect yet. Any issue?

**Comment by joshreisner** [comment]
oops yes when you make a change it needs to be compiled. we do this by following [these instructions](https://github.com/code4recovery/tsml-ui#contributing) -- i'll do it now though

**Comment by Hiro-Tokyo** [comment]
Thanks Josh! I made sure my request is active now. I will make sure the instruction. I may ask you how to do that.

**Pull request merged**
