### PR TITLE
Update ja.ts

### PR DESCRIPTION
**Pull request by Hiro-Tokyo**
I made some Japanese translation changes.

### CODE REVIEW

**Comment by joshreisner** [comment]
thanks hiro! it would be good to build assets as part of this PR. please 

1. install NPM if it is not installled
2. run `npm i` in the project folder
3. run `npx mix --production` in the project folder

i have expanded the section of the readme about developing if you would like to preview your changes locally: https://github.com/code4recovery/tsml-ui#contributing

**Comment by Hiro-Tokyo** [comment]
Thanks Jos! How I can do for this alert, "This branch is out-of-date with the base branch"? Or should I install NPM first?
Screenshot 2023-06-03 at 23 46 22

**Comment by Hiro-Tokyo** [comment]
Thanks Josh! How I can do this alert,"This branch is out-of-date with the base branch"? Or should I install NPM first?
Screenshot 2023-06-03 at 23 46 22

**Comment by joshreisner** [comment]
probably click that "update branch" button

**Comment by Hiro-Tokyo** [comment]
Okay I did it!

**Comment by Hiro-Tokyo** [comment]
Seems reveted!
Screenshot 2023-06-04 at 8 04 41

**Comment by joshreisner** [comment]
i'm not sure what that means, but i'll go ahead and build it this time

ideally next time there would be two files updated - ja.ts and app.js

**Comment by Hiro-Tokyo** [comment]
Thank you Josh! So I do not have to do anymore this time?

**Comment by joshreisner** [comment]
sounds good! yes nothing more to do - it should be updated now

**Comment by Hiro-Tokyo** [comment]
Thanks!

**Comment by Hiro-Tokyo** [comment]
#308

**Pull request merged**
